[package]
name = "nxpkgrepo-auth"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
async-trait.workspace = true
axum-server = { workspace = true }
axum.workspace = true
chrono.workspace = true
hostname = "0.3.1"
lazy_static.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror = "1.0.38"
tokio.workspace = true
tracing.workspace = true
nxpkgrepo-api-client = { workspace = true }
nxpkgrepo-ui.workspace = true
nxpkgrepo-vercel-api = { workspace = true }
nxpkgrepo-vercel-api-mock = { workspace = true }
url = { workspace = true }
webbrowser = { workspace = true }

[dev-dependencies]
port_scanner = { workspace = true }
